### ISSUE TITLE
[REQ] Webhook trigger when the Auto update / Auto restart finish

### ISSUE THREAD

**Issue by ShiNxz** [K4ryuu/CS2-Egg#10]
**Describe the solution you'd like**
Would like to have the option to add a webhook URL (like API) that fires every time the server updates / auto updates or uses the auto restart function when a new version releases, maybe even a variety of payloads like "UPDATE_FINISH" or "UPDATE_STARTS" so we can then handle automations.

**Comment by K4ryuu** [comment]
Greetings,
This is not a regular use of the egg. I pack things in it, that can be used widely, on multiple servers. This would be just a junk in it for the most users. Feel free to create a modified version of the egg for yourself with these features.

Best Regards,
K4ryuu
