### ISSUE TITLE
[BUG] Server marked as yellow state

### ISSUE THREAD

**Issue by Prefix** [K4ryuu/CS2-Egg#3]
![image](https://github.com/user-attachments/assets/c95d8043-c52d-45f0-a164-ee003d523b2d)
![image](https://github.com/user-attachments/assets/6a559158-2ae2-43a0-8b5b-d9c0096f9df2)

Server being shown as yellow, instead of green (something like it's still going up) even it's reachable.
I'm using latest egg
Thats how running server looks like
![image](https://github.com/user-attachments/assets/9ffb06f0-aede-44e5-b5ec-7541cc7fd760)
![image](https://github.com/user-attachments/assets/12ee84f1-afcb-4190-9007-dbdd027a7945)

**Comment by K4ryuu** [comment]
Most probably you changed the start detect text in Eggs, which is by default:

```
{
    "done": "Connection to Steam servers successful"
}
```

Change it back.
I'm mainly running tons of servers with this image at the moment, and all starts properly.

**Comment by Prefix** [comment]
it was because console logs cleaner, I probably filtered out this line
