### ISSUE TITLE
wrong api address 

### ISSUE THREAD

**Issue by szogun1910** [K4ryuu/CS2-Egg#6]
Adding the ip address in the postion of ip address , I get a return message that the address is invalid "http://83.xxx.xxx.xx " "83.xx.xx.xx"

**Comment by K4ryuu** [comment]
You dont use an ip address... You should put the dns name of your panel using HTTPS (example: https://panel.my-domain.com). If you want to override this rule, you can edit the validation rule in your variables for the URL and remove the HTTPS validation regex. But its not recommended to use HTTP.
