### ISSUE TITLE
[BUG] gameinfo.gi no more metamod added

### ISSUE THREAD

**Issue by webpashtet** [K4ryuu/CS2-Egg#7]
After the recent update of cs2 metamod is no longer added to gameinfo

**Comment by K4ryuu** [comment]
Greetings,
I tested the issue and the reference is being added correctly to the file.

**Comment by webpashtet** [comment]
It doesn't work for me, although everything was fine before. The link stopped being added about 2 weeks ago.
I installed the latest version of the egg and now in addition to the broken metamod link I also get an error about logging.
`[KitsuneLab] > Error occurred while executing: [[ $LOG_FILE_ENABLED -eq 1 ]]`

**Comment by K4ryuu** [comment]
Oh.... Makes sense now with the log. Always start with that.

There was multiple bigger updates, but the biggest one comes within a few hours. I recommend you to follow the update guide in order to fix your issue temporary, but from the next version there wont be any problem like this anymore.

Documentation to update: https://docs.kitsune-lab.com/main/cs2-egg

Today's update aims to optimise and enhance the egg greatly.

Appreciate your feedback!

**Comment by K4ryuu** [comment]
![CleanShot 2024-11-22 at 01 47 30@2x](https://github.com/user-attachments/assets/87470e6b-20f1-4124-946d-ae7014416ac1)

You can download the beta branch, which has your issue fixed. ❤️

**Comment by webpashtet** [comment]
> ![CleanShot 2024-11-22 at 01 47 30@2x](https://private-user-images.githubusercontent.com/104531589/388748229-87470e6b-20f1-4124-946d-ae7014416ac1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNTc4MDAsIm5iZiI6MTczMjI1NzUwMCwicGF0aCI6Ii8xMDQ1MzE1ODkvMzg4NzQ4MjI5LTg3NDcwZTZiLTIwZjEtNDEyNC05NDZkLWFlNzAxNDQxNmFjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQwNjM4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjQzYjc5MGJhMmQwNDU5MTRlZjViNTE3YjEyZmFjMWM2ZDFmMzAxYWYyMTE4MzU2Y2JiNTcyOWRlMDZkMDdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KB4YFCjsbktTZdUwr690lIed5KDe5uv_M3LmKv_b540)
> 
> You can download the beta branch, which has your issue fixed as I found it at the end. ❤️

updated the egg, chose the dev image and restarted the server in advance setting the logging parameter to 1 and still do not receive a link to the metamod in gameinfo
![image](https://github.com/user-attachments/assets/cf31267d-73dd-42ca-a7a5-ba5cdfb40a1f)
there is not even a log that the file does not need updating

**Comment by K4ryuu** [comment]
The dev image didn't have this update, only the beta build. However I merged the changes to latest build, so from today you can also use it with the latest image.
